name: Lighthouse CI Result Transformer
description: Handle easily the Lighthouse CI results

inputs:
  resultsPath:
    description: The LightHouse CI outputs.resultsPath
    required: true
  slackWebhookUrl:
    description: The URL of the Slack Webhook

runs:
  using: node16
  main: src/index.js
