name: Static Analysis

on:
  pull_request:
    branches: ['*']

  push:
    branches:
    - main

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Ensure code is linted
        run: yarn lint
